### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by yuta0225y** [yuta0225y/runbreeze#41]
### ■Webアプリの概要
「RunBreeze」は、ランニングやマラソン大会に参加するランナーが、学びやベストプラクティスを投稿・共有できるプラットフォームです。ユーザーは自身の経験や知識を投稿し、他のランナーと情報を交換しながら、より良いランニングライフを目指せます。カテゴリーやタグ機能、投稿内容のAI校正機能により、誰でも気軽に投稿でき、必要な情報を簡単に探せるように設計されています。

### ■1週間辺りの開発に向けられる時間
1週間あたり：40時間

### ■ProjectsのURL
■MVPリリースまで
- [ ] 環境構築
- [ ] Renderデプロイ
- [ ] トップページ
- [ ] ヘッダー
- [ ] フッター
- [ ] ユーザー登録機能
- [ ]  ログイン機能
- [ ] 記事投稿（画像投稿含む）、閲覧、編集、削除機能
- [ ] 記事検索機能
- [ ] コメント投稿、編集、削除機能
- [ ] マイページ
- [ ] プロフィール編集機能
- [ ] ユーザー情報閲覧機能（未ログインでも閲覧可能）
- [ ] ボトムナビゲーション
- [ ] Google アナリティクス
- [ ] ドメイン取得
- [ ] レスポンシブル対応
- [ ] 静的OGP画像

■MVP後
- [ ] いいね機能
- [ ] パスワードリセット
- [ ] Google認証
- [ ] ファビコン作成
- [ ] 利用規約、プライバシーポリシー作成
- [ ] 通知機能
- [ ] 投稿内容のAI校正機能
- [ ] 多言語対応の実装
- [ ] 投稿促進バッチ機能

■MVPレビュー依頼予定日
予定日：2024年11月18日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。

概ね良さそうです。
LGTMです！

**Comment by yuta0225y** [comment]
レビューありがとうございます！

面談予約させていただきます。
引き続きよろしくお願いいたします。
