### ISSUE TITLE
11/21 MVPレビュー依頼

### ISSUE THREAD

**Issue by yuta0225y** [yuta0225y/runbreeze#47]
## 各種情報
サービスの概要とMVPで検証する事柄：
「RunBreeze」は、ランニングやマラソン大会に参加するランナーが、学びやベストプラクティスを投稿・共有できるプラットフォームです。ユーザーは自身の経験や知識を投稿し、他のランナーと情報を交換しながら、より良いランニングライフを目指せます。カテゴリーやタグ機能等により、誰でも気軽に投稿でき、必要な情報を簡単に探せるように設計されています。
MVPでは、記事の作成、投稿、タブや入力による検索ができるところまで実装及び検証しました。

サービス名：RunBreeze
サービスURL：https://runbreeze.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー認証機能（deviseを使用）
- [x] 投稿機能（タイトル、カテゴリー、タグ、画像、参考URLの投稿）
- [x] 検索機能（タイトル、タグ、カテゴリー、アカウント名で検索）

## READMEレビュー時から変更した機能
マイページ機能（投稿管理、ブックマーク、下書き保存）は本リリースに回します。

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by yuta0225y** [comment]
中井講師
レビューいただきありがとうございます！
本リリースに向けて頑張ります😊

引き続きよろしくお願いいたします🙇
